spring:
  application:
    name: zeromesh-ingestion-service

  datasource:
    url: jdbc:h2:file:./zeromeshdb;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 500ms
      connect-timeout: 500ms

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        max.block.ms: 1500          # fail fast if broker unreachable (1.5s instead of default 60s)
        request.timeout.ms: 1500    # socket-level timeout
        delivery.timeout.ms: 3000   # total delivery timeout
    consumer:
      group-id: zeromesh-ingestion-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: ${PORT:8080}

logging:
  level:
    com.zeromesh: INFO
